apiVersion: apps/v1
kind: Deployment
metadata:
  name: bread
  labels:
    app: bread
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bread
  template:
    metadata:
      labels:
        app: bread
    spec:
      containers:
        - name: bread
          image: username/bread:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5